{% set name = "dbt-spark" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fb81fb1d778433789e9d1ec44a8919b39fb8858be25f3af29ed05e144259f5e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - dbt-adapters >=1.7,<2.0
    - dbt-common >=1.10,<2.0
    - python >=3.8
    - pyhive >=0.7.0,<0.8.0
    - sqlparams >=3.0.0
    - thrift >=0.13.0
    - pyspark >=3.0.0,<4.0.0
    - sqlparse >=0.4.2 # not directly required, pinned by Snyk to avoid a vulnerability
    - dbt-core >=1.8.0

test:
  imports:
    - dbt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dbt-labs/dbt-spark
  summary: The Apache Spark adapter plugin for dbt
  license: Apache-2.0
  license_file: License.md

extra:
  recipe-maintainers:
    - rxm7706
    - monaldoj
